org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft, NeoForge & Parchment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.222
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.21-nightly-SNAPSHOT

# Mod Properties
mod_id=expandingtechnologies
mod_name=Expanding Technologies
mod_license=All Rights Reserved
mod_version=1.3.4
mod_group_id=nl.teamdiopside
mod_authors=curryducker, Lars_Mans
mod_description=Expanding Technologies is an addon that expands the Create mod with new features!

# Dependencies
create_minecraft_version = 1.21.1
flywheel_minecraft_version = 1.21.1
create_version = 6.0.10-272
flywheel_version = 1.0.6
ponder_version = 1.0.81
registrate_version = MC1.21-1.3.0+67
mixin_extras_version = 0.4.1