name: Feature Request
description: Tell us about your feature request
title: "[Feature Request]: "
labels: ["enhancement"]
assignees:
  - LarsMans64,curryducker
body:
  - type: textarea
    id: request
    attributes:
      label: Feature Request
      description: Tell us about your request! We don't guarantee that we will actually accept it!
      placeholder: Your very cool feature request!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What version of the mod is this request for?
      options:
        - Fabric
        - Forge
        - Both
    validations:
      required: true